services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eKonsulta_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./res:/var/www/html/res
      - ./files:/var/www/html/files
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: konsulta
      MYSQL_USER: ekon_app_user
      MYSQL_PASSWORD: xxx123
      ENV_TYPE: development
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - eKonsulta_network

  mysql:
    image: mysql:5.7
    container_name: eKonsulta_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: roottoor
      MYSQL_DATABASE: konsulta
    command: 
      - mysqld
      - --sql-mode=
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --lower_case_table_names=1
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./konsulta_010826.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - eKonsulta_network

volumes:
  mysql-data:

networks:
  eKonsulta_network:
    driver: bridge
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

